"""Add fields to EventModel

Revision ID: 4866323465e4
Revises: db6eb5572d96
Create Date: 2024-11-12 01:31:04.076304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4866323465e4'
down_revision: Union[str, None] = 'db6eb5572d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EventModel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_notified_time_left', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_repeatable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_foreign_key("EventAuthor", 'BoyModel', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EventModel', schema=None) as batch_op:
        batch_op.drop_constraint("EventAuthor", type_='foreignkey')
        batch_op.drop_column('create_date')
        batch_op.drop_column('is_repeatable')
        batch_op.drop_column('is_notified_time_left')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
