"""Add chat model

Revision ID: 6cace797ee57
Revises: 4866323465e4
Create Date: 2025-01-29 01:17:28.889058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cace797ee57'
down_revision: Union[str, None] = '4866323465e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', 'SUPERGROUP', 'CHANNEL', name='chattypeenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChatModel')
    # ### end Alembic commands ###
