"""Add event model

Revision ID: db6eb5572d96
Revises: 3a8994e8225b
Create Date: 2024-11-12 00:03:19.176952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6eb5572d96'
down_revision: Union[str, None] = '3a8994e8225b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventModel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BoyEventModel',
    sa.Column('boy_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boy_id'], ['BoyModel.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['EventModel.id'], ),
    sa.PrimaryKeyConstraint('boy_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BoyEventModel')
    op.drop_table('EventModel')
    # ### end Alembic commands ###
